name: First CI Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "hello this is checkout"

      - name: Run a command
        run: echo "Building application"

      - name: Run multiple commands
        run: | 
          echo "This step runs several shell commands."
          echo "Today's runner is: $RUNNER_OS"
          echo "The repository is: $GITHUB_REPOSITORY"
