name: First CI Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "hello this is checkout"

      - name: Run a command
        run: echo "Building application"

      - name: Run tests
        run: | #use multiple cmds 
         echo "Running test1"
         echo "Running test2"
         echo "Running test3"
